### ISSUE TITLE
Cv25519 please?? 

### ISSUE THREAD

**Issue by dotfrankruan** [cuihaoleo/gpg-fingerprint-filter-gpu#2]
Hello, I am using Ed25519 for signature and RSA4096 for encryption, but RSA is terribly slow compared to ECDSA, but it seems like that I can't generate a Cv25519 key for encryption? Why?

**Comment by cuihaoleo** [comment]
Implemented in #3  and commit 0a272d8a192cfc77ebc3b551d4b4ededfb8d75e7 .

**Comment by cuihaoleo** [comment]
Note: use `-a cv25519` to generate a cv25519 key (which can be used as a subkey but the master key).
